// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIKpw-4P7yzrc3_aibbBmQMg3Ku8hxHsE',
    appId: '1:641491537556:web:5b88610993ab669c776e81',
    messagingSenderId: '641491537556',
    projectId: 'firstproject-1fad0',
    authDomain: 'firstproject-1fad0.firebaseapp.com',
    storageBucket: 'firstproject-1fad0.firebasestorage.app',
    measurementId: 'G-DEYBJ69Z0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNMbextHxW8E6dpAcDYqp0xJozc9U_-U',
    appId: '1:641491537556:android:a6edbc5c2002eeba776e81',
    messagingSenderId: '641491537556',
    projectId: 'firstproject-1fad0',
    storageBucket: 'firstproject-1fad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUKEMQGx95kAoKq2TDVThJwVUzOKKL6Y',
    appId: '1:641491537556:ios:c5a5b45f721b8b72776e81',
    messagingSenderId: '641491537556',
    projectId: 'firstproject-1fad0',
    storageBucket: 'firstproject-1fad0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgUKEMQGx95kAoKq2TDVThJwVUzOKKL6Y',
    appId: '1:641491537556:ios:c5a5b45f721b8b72776e81',
    messagingSenderId: '641491537556',
    projectId: 'firstproject-1fad0',
    storageBucket: 'firstproject-1fad0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIKpw-4P7yzrc3_aibbBmQMg3Ku8hxHsE',
    appId: '1:641491537556:web:69d8d14a625a841e776e81',
    messagingSenderId: '641491537556',
    projectId: 'firstproject-1fad0',
    authDomain: 'firstproject-1fad0.firebaseapp.com',
    storageBucket: 'firstproject-1fad0.firebasestorage.app',
    measurementId: 'G-BY7V5KR47S',
  );
}
